const CONTACT={phone:'0561 84 14 40',tel:'tel:0561841440',wa:'https://wa.me/213561841440',email:'cleanplus.dz@gmail.com',addr:'Aïn Naâdja, Alger 16048',map:'https://www.google.com/maps/search/?api=1&query=Ain+Naadja+Alger',insta:'cleanplus_dz',instaUrl:'https://www.instagram.com/cleanplus_dz/'};
const STD_C=[['Tenir hors de portée des enfants.','يُحفظ بعيدا عن متناول الأطفال.'],['Éviter le contact avec les yeux ; en cas de projection, rincer abondamment à l\'eau.','تجنّبوا ملامسة العينين وعند التعرّض اشطفوا بوفرة بالماء.'],['Ne pas ingérer. Conserver dans l\'emballage d\'origine, à l\'abri de la chaleur.','لا يُبتلع. يُحفظ في عبوته الأصلية بعيدا عن الحرارة.']];
const CHEM_C=[['Ne jamais mélanger avec un autre produit d\'entretien (javel, détartrant, acide…) : risque de gaz dangereux.','لا تخلطوه أبدا بأي منتج تنظيف آخر (جافيل، مزيل كلس، أحماض…): خطر غازات ضارّة.'],['Porter des gants, aérer la pièce, éviter tout contact avec la peau et les yeux.','ارتدوا القفازات وهوّوا المكان وتجنّبوا ملامسة الجلد والعينين.'],['Tenir hors de portée des enfants.','يُحفظ بعيدا عن متناول الأطفال.']];
const PRODUCTS={
 linge:{slug:'linge',accent:'#ffb84d',name:'Liquide linge — Savon de Marseille 3 L',short2:'Liquide linge',ar:'سائل غسيل الملابس — صابون مرسيليا 3 لتر',tag:'Linge',tagAr:'الملابس',
  img:'img/linge.webp',photo:'img/camp-linge.jpg',c1:'#ffb84d',c2:'#9a4d00',dark:false,
  short:'Le parfum du savon de Marseille, 40 doses, pour la machine.',shortAr:'عطر صابون مرسيليا، 40 جرعة، للغسالة.',
  desc:'Le liquide linge Clean Plus au parfum de savon de Marseille élimine efficacement les taches et laisse sur les vêtements une odeur fraîche qui dure, dès un seul lavage. Bouteille de 3 L, 40 doses, pour machine automatique et semi-automatique.',
  descAr:'سائل غسيل الملابس كلين بلوس بعطر صابون مرسيليا يزيل البقع بفعالية ويترك على الملابس رائحة منعشة تدوم، من غسلة واحدة فقط. عبوة 3 لتر، 40 جرعة، للغسالة الأوتوماتيكية والشبه أوتوماتيكية.',
  areas:[['40 doses','40 جرعة','🧺'],['Machine auto & semi-auto','غسالة أوتوماتيكية وشبه أوتوماتيكية','🫧'],['Savon de Marseille','صابون مرسيليا','🧼'],['Nouveau','جديد','✨']],
  fmt:'3 L · 40 doses',uses:[['Doser selon la charge et la salissure (voir la mesure et l\'emballage).','حدّدوا الجرعة حسب الحمولة ودرجة الاتساخ (انظروا سدادة القياس والعبوة).'],['Verser dans le bac à lessive ou le tambour de la machine.','صبّوها في حجرة المنظف أو حوض الغسالة.'],['Lancer le programme adapté au linge.','شغّلوا البرنامج المناسب للملابس.']],cautions:STD_C},
 vaisselle:{slug:'vaisselle',accent:'#ffd21f',name:'Liquide vaisselle Double Force — Citron 710 ml',short2:'Liquide vaisselle',ar:'سائل غسيل الأواني دبل فورس — ليمون 710 مل',tag:'Vaisselle',tagAr:'الأواني',
  img:'img/vaisselle.webp',photo:'img/camp-vaisselle.jpg',c1:'#ffe066',c2:'#8a6a00',dark:true,
  short:'Double Force au citron : adieu les graisses.',shortAr:'دبل فورس بالليمون: وداعا للدهون.',
  desc:'Le liquide vaisselle Clean Plus Double Force, à la formule citron efficace, élimine facilement les graisses et les saletés les plus tenaces et offre à votre vaisselle propreté et brillance sans effort. Flacon de 710 ml.',
  descAr:'سائل غسيل الأواني كلين بلوس دبل فورس بتركيبة الليمون الفعالة يزيل أصعب الدهون والأوساخ بسهولة ويمنح أوانيك نظافة ولمعانا دون عناء. قارورة 710 مل.',
  areas:[['Double Force','دبل فورس','💪'],['Parfum citron','عطر الليمون','🍋'],['Anti-graisses','ضد الدهون','💧']],
  fmt:'710 ml',uses:[['Verser une petite quantité sur une éponge humide ou dans l\'eau de lavage.','صبّوا كمية صغيرة على إسفنجة مبلّلة أو في ماء الغسيل.'],['Laver la vaisselle, les verres et les casseroles.','اغسلوا الأواني والكؤوس والقدور.'],['Rincer abondamment à l\'eau claire.','اشطفوا جيدا بالماء النظيف.']],cautions:STD_C},
 lavesol:{slug:'lavesol',accent:'#ff5a5f',name:'Lave-sol 1 L — Senteur fleur blanche',short2:'Lave-sol',ar:'منظف الأرضيات 1 لتر — برائحة الورد الأبيض',tag:'Sols',tagAr:'الأرضيات',
  img:'img/lavesol.webp',photo:'img/camp-lavesol.jpg',c1:'#ff5a5f',c2:'#7c0a12',dark:false,
  short:'Nettoie et désinfecte : sols propres qui brillent.',shortAr:'ينظّف ويعقّم: أرضيات نظيفة ولامعة.',
  desc:'Le lave-sol Clean Plus offre à vos sols une propreté profonde, un éclat visible et un parfum de fleur blanche frais et durable. Il nettoie et désinfecte. Flacon de 1 L.',
  descAr:'منظف الأرضيات كلين بلوس يمنح أرضياتك نظافة عميقة ولمعانا واضحا ورائحة الورد الأبيض المنعشة التي تدوم. ينظّف ويعقّم. قارورة 1 لتر.',
  areas:[['Nettoie & désinfecte','ينظّف ويعقّم','🛡️'],['Fleur blanche','الورد الأبيض','🌸'],['Éclat visible','لمعان واضح','✨']],
  fmt:'1 L',uses:[['Diluer la dose indiquée sur l\'emballage dans un seau d\'eau.','خفّفوا الجرعة المدوّنة على العبوة في دلو ماء.'],['Laver le sol avec une serpillière.','امسحوا الأرضية بممسحة.'],['Laisser sécher à l\'air.','اتركوها تجفّ في الهواء.']],cautions:STD_C},
 javel:{slug:'javel',accent:'#4aa8ff',name:'Javel — 750 ml et 5 L',short2:'Javel',ar:'ماء الجافيل — 750 مل و5 لتر',tag:'Désinfection',tagAr:'التعقيم',
  img:'img/javel5.webp',hero:'img/mascot_javel.webp',photo:'img/camp-javel750.jpg',c1:'#4aa8ff',c2:'#0a3f9e',dark:false,
  sizes:[['750 ml','img/mascot_javel.webp'],['5 L','img/javel5.webp']],
  short:'Désinfectant et nettoyant : adieu les germes.',shortAr:'مطهّر ومنظّف: وداعا للجراثيم.',
  desc:'L\'eau de javel Clean Plus, désinfectante et nettoyante, aide à éliminer les germes et assure une propreté idéale dans tous les coins de la maison. Disponible en 750 ml et en bidon de 5 L (13° chlorométrique).',
  descAr:'ماء الجافيل كلين بلوس المطهّر والمنظّف بتركيبته الفعالة يساعد على القضاء على الجراثيم ويوفر لك نظافة مثالية لكل زوايا المنزل بكل سهولة. متوفر بحجم 750 مل وبعبوة 5 لتر (13° كلوري).',
  areas:[['Désinfectant','مطهّر','🦠'],['Nettoyant','منظّف','🧴'],['750 ml & 5 L','750 مل و5 لتر','📦'],['13° chlorométrique','13° كلوري','⚗️']],
  fmt:'750 ml · 5 L',uses:[['Diluer dans l\'eau selon l\'usage souhaité.','خفّفوه بالماء حسب الاستعمال المطلوب.'],['Appliquer sur la surface, laisser agir quelques minutes.','ضعوه على السطح واتركوه دقائق ليعمل.'],['Rincer abondamment à l\'eau claire.','اشطفوا جيدا بالماء النظيف.']],
  cautions:[['Ne jamais mélanger la javel avec un détartrant, un acide ou de l\'ammoniaque : risque de gaz dangereux.','لا تخلطوا الجافيل أبدا بمزيل الكلس أو الأحماض أو الأمونياك: خطر غازات ضارّة.'],['Utiliser dans un endroit aéré, avec des gants. Éviter le contact avec les yeux et la peau.','استعملوه في مكان مهوّى مع القفازات وتجنّبوا ملامسة العينين والجلد.'],['Tenir hors de portée des enfants.','يُحفظ بعيدا عن متناول الأطفال.']]},
 esprit:{slug:'esprit',accent:'#ff4b4b',name:'Esprit de sel 750 ml',short2:'Esprit de sel',ar:'روح الملح 750 مل',tag:'Canalisations',tagAr:'المجاري',
  img:'img/mascot_esprit.webp',hero:'img/mascot_esprit.webp',photo:'img/camp-esprit.jpg',c1:'#ff4b4b',c2:'#6d0810',dark:false,
  short:'Rapide et efficace contre les pires bouchons.',shortAr:'سريع وفعّال ضد أصعب الانسدادات.',
  desc:'L\'esprit de sel Clean Plus, à la formule efficace, s\'attaque aux bouchons les plus difficiles. Rapide et efficace, il est conçu pour l\'entretien des éviers et des canalisations. Flacon de 750 ml.',
  descAr:'روح الملح كلين بلوس بتركيبته الفعالة يواجه أصعب الانسدادات. سريع وفعّال، مخصص للعناية بالأحواض وقنوات المجاري. قارورة 750 مل.',
  areas:[['Rapide & efficace','سريع وفعّال','⚡'],['Éviers','الأحواض','🚰'],['Canalisations','قنوات المجاري','🔧']],
  fmt:'750 ml',uses:[['Suivre le mode d\'emploi figurant sur l\'emballage.','اتبعوا طريقة الاستعمال المدوّنة على العبوة.'],['Verser la dose indiquée dans la canalisation, laisser agir.','صبّوا الجرعة المحدّدة في القناة واتركوها تعمل.'],['Rincer abondamment à l\'eau.','اشطفوا بوفرة بالماء.']],cautions:CHEM_C},
 detartrant:{slug:'detartrant',accent:'#29a7e1',name:'Détartrant actif 750 ml — Detart-Actif',short2:'Détartrant actif',ar:'مزيل الكلس النشط 750 مل — نظاف ولماع',tag:'Sanitaires',tagAr:'الحمّامات',
  img:'img/detartrant.webp',photo:'img/camp-detartrant.jpg',c1:'#7fd3ff',c2:'#0a4d9e',dark:false,
  short:'Plus fort que toutes les taches, propre et brillant.',shortAr:'أقوى من كل البقع، نظيف ولامع.',
  desc:'Le détartrant Clean Plus Detart-Actif élimine les taches et le calcaire des sanitaires et des robinetteries pour un résultat propre et brillant. Flacon de 750 ml, nouvelle formule.',
  descAr:'مزيل الكلس النشط كلين بلوس يزيل البقع والكلس عن الحمّامات والحنفيات لنتيجة نظيفة ولامعة. قارورة 750 مل، تركيبة جديدة.',
  areas:[['Anti-calcaire','ضد الكلس','🚿'],['Robinets & WC','حنفيات ومراحيض','🚽'],['Brillance','لمعان','✨']],
  fmt:'750 ml',uses:[['Appliquer sur la surface à détartrer (robinet, lavabo, WC).','ضعوه على السطح المراد إزالة الكلس عنه (حنفية، مغسلة، مرحاض).'],['Laisser agir quelques minutes puis frotter.','اتركوه دقائق ثم افركوا.'],['Rincer abondamment.','اشطفوا جيدا.']],cautions:CHEM_C},
 savon:{slug:'savon',accent:'#ffd21f',name:'Savon mains — Citron 5 L',short2:'Savon mains',ar:'صابون اليدين — عطر الليمون 5 لتر',tag:'Mains',tagAr:'اليدين',
  img:'img/savon.webp',hero:'img/mascot_savon.webp',photo:'img/camp-savon.jpg',c1:'#ffd21f',c2:'#8a6200',dark:true,
  short:'Nettoie en profondeur, préserve la douceur.',shortAr:'ينظّف بعمق ويحافظ على النعومة.',
  desc:'Le savon liquide pour les mains Clean Plus, au parfum de citron, offre un nettoyage en profondeur tout en préservant la douceur des mains. Format familial de 5 L.',
  descAr:'صابون اليدين السائل كلين بلوس بعطر الليمون يمنحك تنظيفا عميقا لليدين مع الحفاظ على نعومتهما. عبوة عائلية 5 لتر.',
  areas:[['Parfum citron','عطر الليمون','🍋'],['Douceur des mains','نعومة اليدين','🤲'],['Format familial 5 L','عبوة عائلية 5 لتر','👨‍👩‍👧']],
  fmt:'5 L · format familial',uses:[['Verser un peu de savon dans la paume de la main.','ضعوا قليلا من الصابون في راحة اليد.'],['Frotter les mains avec soin en ajoutant de l\'eau.','افركوا اليدين بعناية مع إضافة الماء.'],['Rincer à l\'eau claire.','اشطفوا بالماء النظيف.']],cautions:STD_C},
 eau:{slug:'eau',accent:'#5ec4ff',name:'Eau distillée 720 ml',short2:'Eau distillée',ar:'ماء مقطّر 720 مل',tag:'Appareils',tagAr:'الأجهزة',
  img:'img/eau.webp',photo:'img/camp-eau.jpg',c1:'#8fd3ff',c2:'#0a3f8f',dark:false,
  short:'Pure et sans impuretés : protège vos appareils du calcaire.',shortAr:'نقية وخالية من الشوائب: تحمي أجهزتك من التكلس.',
  desc:'L\'eau distillée Clean Plus, d\'une grande pureté et sans impuretés, aide à protéger vos appareils (fer à repasser…) du calcaire et préserve leurs performances. Bouteille de 720 ml.',
  descAr:'الماء المقطّر كلين بلوس بنقاء عالٍ وخالٍ من الشوائب يساعد على حماية أجهزتك (مكواة…) من التكلس ويحافظ على أدائها. قارورة 720 مل.',
  areas:[['Sans impuretés','خالٍ من الشوائب','💎'],['Fer à repasser','المكواة','♨️'],['Anti-calcaire','ضد التكلس','🛡️']],
  fmt:'720 ml',uses:[['Verser dans le réservoir de l\'appareil (fer à repasser, appareil à vapeur…).','صبّوه في خزان الجهاز (مكواة، جهاز بخار…).'],['Se référer à la notice de l\'appareil pour le remplissage.','ارجعوا إلى دليل الجهاز للتعبئة.']],
  cautions:[['Usage technique : non destinée à la boisson.','استعمال تقني: غير مخصص للشرب.'],['Conserver bien fermée, à l\'abri de la chaleur.','تُحفظ مغلقة جيدا بعيدا عن الحرارة.'],['Tenir hors de portée des enfants.','يُحفظ بعيدا عن متناول الأطفال.']]}
};
const ORDER=['linge','vaisselle','lavesol','javel','esprit','detartrant','savon','eau'];
const NEEDS=[
 {id:'linge',em:'👕',t:['Laver le linge','غسيل الملابس'],s:['Machine, 40 doses','غسالة، 40 جرعة'],p:['linge'],tips:[['Le liquide linge au savon de Marseille est prévu pour les machines automatiques et semi-automatiques.','سائل الغسيل بصابون مرسيليا مخصص للغسالات الأوتوماتيكية والشبه أوتوماتيكية.'],['Dosez selon la charge (40 doses par bouteille de 3 L).','حدّدوا الجرعة حسب الحمولة (40 جرعة في عبوة 3 لتر).']]},
 {id:'vaisselle',em:'🍽️',t:['Vaisselle grasse','أواني دهنية'],s:['Double Force citron','دبل فورس بالليمون'],p:['vaisselle'],tips:[['Double Force au citron : conçu pour venir à bout des graisses.','دبل فورس بالليمون: مخصص للتغلب على الدهون.'],['Une petite quantité suffit, puis rincez abondamment.','كمية صغيرة تكفي ثم اشطفوا جيدا.']]},
 {id:'sols',em:'🧽',t:['Sols brillants','أرضيات لامعة'],s:['Fleur blanche','الورد الأبيض'],p:['lavesol'],tips:[['Le lave-sol nettoie et désinfecte, avec un parfum de fleur blanche.','منظف الأرضيات ينظّف ويعقّم بعطر الورد الأبيض.'],['Diluez selon les indications de l\'emballage.','خفّفوه حسب إرشادات العبوة.']]},
 {id:'germes',em:'🦠',t:['Éliminer les germes','القضاء على الجراثيم'],s:['Javel 750 ml et 5 L','جافيل 750 مل و5 لتر'],p:['javel'],tips:[['La javel Clean Plus est désinfectante et nettoyante, disponible en 750 ml et 5 L.','جافيل كلين بلوس مطهّر ومنظّف، متوفر بحجم 750 مل و5 لتر.'],['Ne la mélangez jamais avec un détartrant ou un autre produit.','لا تخلطوه أبدا بمزيل الكلس أو بمنتج آخر.']]},
 {id:'bouchon',em:'🚰',t:['Déboucher un évier','فتح انسداد الحوض'],s:['Esprit de sel','روح الملح'],p:['esprit'],tips:[['Rapide et efficace contre les bouchons les plus difficiles.','سريع وفعّال ضد أصعب الانسدادات.'],['Gants et aération obligatoires ; ne jamais mélanger avec la javel.','القفازات والتهوية ضروريان؛ لا تخلطوه أبدا بالجافيل.']]},
 {id:'calcaire',em:'🚿',t:['Détartrer WC & robinets','إزالة الكلس'],s:['Detart-Actif','نظاف ولماع'],p:['detartrant'],tips:[['Le détartrant actif élimine taches et calcaire pour un résultat brillant.','مزيل الكلس النشط يزيل البقع والكلس لنتيجة لامعة.'],['Rincez abondamment après usage.','اشطفوا جيدا بعد الاستعمال.']]},
 {id:'mains',em:'🧼',t:['Se laver les mains','غسل اليدين'],s:['Savon citron 5 L','صابون بالليمون 5 لتر'],p:['savon'],tips:[['Nettoyage en profondeur en préservant la douceur des mains.','تنظيف عميق مع الحفاظ على نعومة اليدين.'],['Format familial de 5 L, idéal pour toute la maison.','عبوة عائلية 5 لتر مثالية لكل البيت.']]},
 {id:'fer',em:'♨️',t:['Fer à repasser & appareils','المكواة والأجهزة'],s:['Eau distillée','ماء مقطّر'],p:['eau'],tips:[['L\'eau distillée aide à protéger vos appareils du calcaire.','الماء المقطّر يساعد على حماية أجهزتك من الكلس.'],['Suivez toujours la notice de votre appareil.','اتبعوا دائما دليل استعمال جهازكم.']]}
];

const WILAYAS=['Adrar','Chlef','Laghouat','Oum El Bouaghi','Batna','Béjaïa','Biskra','Béchar','Blida','Bouira','Tamanrasset','Tébessa','Tlemcen','Tiaret','Tizi Ouzou','Alger','Djelfa','Jijel','Sétif','Saïda','Skikda','Sidi Bel Abbès','Annaba','Guelma','Constantine','Médéa','Mostaganem','M\'Sila','Mascara','Ouargla','Oran','El Bayadh','Illizi','Bordj Bou Arréridj','Boumerdès','El Tarf','Tindouf','Tissemsilt','El Oued','Khenchela','Souk Ahras','Tipaza','Mila','Aïn Defla','Naâma','Aïn Témouchent','Ghardaïa','Relizane','Timimoun','Bordj Badji Mokhtar','Ouled Djellal','Béni Abbès','In Salah','In Guezzam','Touggourt','Djanet','El M\'Ghair','El Meniaa'];
const WILAYAS_AR=['أدرار','الشلف','الأغواط','أم البواقي','باتنة','بجاية','بسكرة','بشار','البليدة','البويرة','تمنراست','تبسة','تلمسان','تيارت','تيزي وزو','الجزائر','الجلفة','جيجل','سطيف','سعيدة','سكيكدة','سيدي بلعباس','عنابة','قالمة','قسنطينة','المدية','مستغانم','المسيلة','معسكر','ورقلة','وهران','البيض','إليزي','برج بوعريريج','بومرداس','الطارف','تندوف','تيسمسيلت','الوادي','خنشلة','سوق أهراس','تيبازة','ميلة','عين الدفلى','النعامة','عين تموشنت','غرداية','غليزان','تيميمون','برج باجي مختار','أولاد جلال','بني عباس','عين صالح','عين قزام','تقرت','جانت','المغير','المنيعة'];
